default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bitewheels_development
  username: <%= ENV["BITEWHEELS_DATABASE_USERNAME"] %>
  password: <%= ENV["BITEWHEELS_DATABASE_PASSWORD"] %>
  host: <%= ENV["BITEWHEELS_DATABASE_HOST"] %>  # usually localhost

test:
  <<: *default
  database: bitewheels_test
  username: <%= ENV["BITEWHEELS_DATABASE_USERNAME"] %>
  password: <%= ENV["BITEWHEELS_DATABASE_PASSWORD"] %>
  host: <%= ENV["BITEWHEELS_DATABASE_HOST"] %>

production:
  <<: *default
  database: bitewheels_production
  username: <%= ENV["BITEWHEELS_DATABASE_USERNAME"] %>
  password: <%= ENV["BITEWHEELS_DATABASE_PASSWORD"] %>
  host: <%= ENV["BITEWHEELS_DATABASE_HOST"] %>
